// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okishlqrjdfqwyhcqmvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9raXNobHFyamRmcXd5aGNxbXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjEzNTksImV4cCI6MjA3MzkzNzM1OX0.JH9yoqDvA5AhDDnXN_42PLaCaqia9jX-gcR7ITFV53Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});