// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwsgmuchbyucoxwcbubq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3c2dtdWNoYnl1Y294d2NidWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTE5NTcsImV4cCI6MjA1ODY4Nzk1N30.UVEr9mo3s90a8vldf-kKWO3PJ66xYIdX4pfUPoJspqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);